# Generated by Django 5.1.2 on 2024-10-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caratulados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('nro_expediente', models.CharField(max_length=100)),
                ('provincia', models.CharField(choices=[('caba', 'C.A.B.A'), ('provincia', 'Provincia')], max_length=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_limite', models.DateField()),
            ],
        ),
    ]
