# Generated by Django 5.1.2 on 2024-10-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caratulado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caratulados',
            name='evento',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=25, null=True),
        ),
    ]
