# Generated by Django 5.1.2 on 2024-10-29 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caratulado', '0002_caratulados_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='caratulados',
            name='completado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='caratulados',
            name='fecha_inicio',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='caratulados',
            name='fecha_limite',
            field=models.DateTimeField(),
        ),
    ]
