# Generated by Django 5.1.2 on 2024-10-29 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caratulado', '0003_caratulados_completado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caratulados',
            name='fecha_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='caratulados',
            name='fecha_limite',
            field=models.DateField(),
        ),
    ]
