# Generated by Django 5.1.2 on 2024-10-29 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caratulado', '0004_alter_caratulados_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caratulados',
            name='apellido',
        ),
        migrations.AlterField(
            model_name='caratulados',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
