# Generated by Django 5.1.2 on 2024-10-29 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caratulado', '0005_remove_caratulados_apellido_alter_caratulados_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='caratulados',
            name='jurisdiccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='caratulados',
            name='tribunal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='caratulados',
            name='evento',
            field=models.CharField(choices=[('acompañar estudios', 'Acompañar estudios'), ('denuncia fecha de turno', 'Denuncia fecha de turno'), ('acompañar documentacion', 'Acompañar documentacion'), ('intimacion de pago', 'Intimacion de pago'), ('sentencia interlocutoria', 'Sentencia interlocutoria')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='caratulados',
            name='provincia',
            field=models.CharField(choices=[('caba', 'C.A.B.A'), ('provincia', 'Provincia de Buenos Aires')], max_length=10),
        ),
    ]
