# Generated by Django 5.1.2 on 2024-10-29 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caratulado', '0006_caratulados_jurisdiccion_caratulados_tribunal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caratulados',
            name='fecha_inicio',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='caratulados',
            name='fecha_limite',
            field=models.DateTimeField(),
        ),
    ]
