# Generated by Django 5.1.2 on 2024-10-30 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caratulado', '0008_alter_caratulados_tribunal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caratulados',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caratulados',
            name='fecha_limite',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caratulados',
            name='provincia',
            field=models.CharField(blank=True, choices=[('caba', 'C.A.B.A'), ('provincia', 'Provincia de Buenos Aires')], max_length=10, null=True),
        ),
    ]
